CREATE TABLE IF NOT EXISTS OrderDisputes (
    id CHAR(36) PRIMARY KEY,
    orderId CHAR(36),
    customOrderRequestId CHAR(36),
    hireRequestId CHAR(36),
    deliveryOrderId CHAR(36),
    reporterId CHAR(36) NOT NULL,
    reporterRole TEXT NOT NULL,
    reportedUserId CHAR(36) NOT NULL,
    driverId CHAR(36),
    issueCategory TEXT NOT NULL,
    description TEXT NOT NULL,
    photoUrl TEXT,
    requestedAction TEXT NOT NULL,
    adminStatus TEXT NOT NULL,
    adminNotes TEXT,
    resolutionType TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (orderId) REFERENCES Orders (id),
    FOREIGN KEY (customOrderRequestId) REFERENCES CustomOrderRequests (id),
    FOREIGN KEY (hireRequestId) REFERENCES HireRequests (id),
    FOREIGN KEY (deliveryOrderId) REFERENCES DeliveryOrders (id),
    FOREIGN KEY (reporterId) REFERENCES Users (id),
    FOREIGN KEY (reportedUserId) REFERENCES Users (id),
    FOREIGN KEY (driverId) REFERENCES Users (id)
);